[theme]
backgroundColor="#284b63"
textColor="black"
primaryColor="darkGoldenrod"
secondaryColor="darkGoldenrod"
font= "montserrat"

baseRadius="full"

[theme.sidebar]
backgroundColor="#d9d9d9"

primaryColor="darkGoldenrod"
showWidgetBorder=true
showSideBarBorder=true
baseRadius="full"
font= "montserrat"
